In [14]:
import  pandas as pd

df1 = pd.read_csv("data/电商数据.csv")

df1.isnull()
df1.bfill()


df1.duplicated()
df1.drop_duplicates(subset="用户ID")

,用户ID,商品名称,商品类别,数量,单价(元),总价(元),下单时间,收货省份,收货城市,订单状态
0,10086,无线蓝牙耳机,数码配件,1,89.0,89.0,2026-07-23 09:15:32,浙江,杭州,已发货
1,10087,纯棉短袖T恤,男装,2,59.9,119.8,2026-07-23 09:28:41,广东,深圳,已付款
2,10088,不锈钢保温杯500ml,家居用品,1,45.5,45.5,2026-07-23 10:02:18,北京,北京,已完成
3,10089,机械键盘RGB背光,电脑外设,1,299.0,299.0,2026-07-23 10:35:55,上海,上海,已发货
4,10090,婴儿湿巾80抽*5包,母婴用品,3,28.0,84.0,2026-07-23 11:12:07,江苏,南京,已付款
5,10091,运动跑步鞋男款,运动鞋,1,199.0,199.0,2026-07-23 11:48:23,四川,成都,已完成
6,10092,维C咀嚼片100片,保健品,2,39.9,79.8,2026-07-23 12:20:14,湖北,武汉,已取消
7,10093,USB-C数据线2米,数码配件,3,15.0,45.0,2026-07-23 13:05:49,福建,厦门,已发货
8,10094,全麦面包1kg装,食品零食,1,22.5,22.5,2026-07-23 14:18:36,山东,青岛,已完成
9,10095,便携式榨汁机,小家电,1,129.0,129.0,2026-07-23 15:42:11,河南,郑州,已付款
10,10096,防晒喷雾SPF50+,美妆护肤,2,49.9,99.8,2026-07-23 16:30:28,湖南,长沙,已发货
11,10097,瑜伽垫加厚防滑,运动户外,1,69.0,69.0,2026-07-23 17:15:03,陕西,西安,已完成
12,10098,儿童绘本套装10册,图书音像,1,88.0,88.0,2026-07-23 18:08:45,甘肃,平凉,已付款
13,10099,车载手机支架,汽车配件,1,25.0,25.0,2026-07-23 19:22:17,辽宁,沈阳,已发货
14,10100,电动牙刷套装,个护健康,1,159.0,159.0,2026-07-23 20:55:39,安徽,NaN,已完成

In [23]:
import  pandas as pd

df2 = pd.read_csv("data/电商数据.csv")


df2['单价(元)'] = df2['单价(元)'].abs()
df2

,用户ID,商品名称,商品类别,数量,单价(元),总价(元),下单时间,收货省份,收货城市,订单状态
0,10086,无线蓝牙耳机,数码配件,1,89.0,89.0,2026-07-23 09:15:32,浙江,杭州,已发货
1,10087,纯棉短袖T恤,男装,2,59.9,119.8,2026-07-23 09:28:41,广东,深圳,已付款
2,10088,不锈钢保温杯500ml,家居用品,1,45.5,45.5,2026-07-23 10:02:18,北京,北京,已完成
3,10089,机械键盘RGB背光,电脑外设,1,299.0,299.0,2026-07-23 10:35:55,上海,上海,已发货
4,10090,婴儿湿巾80抽*5包,母婴用品,3,28.0,84.0,2026-07-23 11:12:07,江苏,南京,已付款
5,10091,运动跑步鞋男款,运动鞋,1,199.0,199.0,2026-07-23 11:48:23,四川,成都,已完成
6,10092,维C咀嚼片100片,保健品,2,39.9,79.8,2026-07-23 12:20:14,湖北,武汉,已取消
7,10093,USB-C数据线2米,数码配件,3,15.0,45.0,2026-07-23 13:05:49,福建,厦门,已发货
8,10094,全麦面包1kg装,食品零食,1,22.5,22.5,2026-07-23 14:18:36,山东,青岛,已完成
9,10095,便携式榨汁机,小家电,1,129.0,129.0,2026-07-23 15:42:11,河南,郑州,已付款
10,10096,防晒喷雾SPF50+,美妆护肤,2,49.9,99.8,2026-07-23 16:30:28,湖南,长沙,已发货
11,10097,瑜伽垫加厚防滑,运动户外,1,69.0,69.0,2026-07-23 17:15:03,陕西,西安,已完成
12,10098,儿童绘本套装10册,图书音像,1,88.0,88.0,2026-07-23 18:08:45,甘肃,平凉,已付款
13,10099,车载手机支架,汽车配件,1,25.0,25.0,2026-07-23 19:22:17,辽宁,沈阳,已发货
14,10100,电动牙刷套装,个护健康,1,159.0,159.0,2026-07-23 20:55:39,安徽,NaN,已完成
15,10100,电动牙刷套装,个护健康,1,159.0,159.0,2026-07-23 20:55:39,安徽,合肥,已完成

In [26]:
import  pandas as pd

df3 = pd.read_csv("data/电商数据.csv")

df3['下单时间'] = df3['下单时间'].str.replace('/','-')
df3

,用户ID,商品名称,商品类别,数量,单价(元),总价(元),下单时间,收货省份,收货城市,订单状态
0,10086,无线蓝牙耳机,数码配件,1,-89.0,89.0,2026-07-23 09:15:32,浙江,杭州,已发货
1,10087,纯棉短袖T恤,男装,2,59.9,119.8,2026-07-23 09:28:41,广东,深圳,已付款
2,10088,不锈钢保温杯500ml,家居用品,1,45.5,45.5,2026-07-23 10:02:18,北京,北京,已完成
3,10089,机械键盘RGB背光,电脑外设,1,299.0,299.0,2026-07-23 10:35:55,上海,上海,已发货
4,10090,婴儿湿巾80抽*5包,母婴用品,3,28.0,84.0,2026-07-23 11:12:07,江苏,南京,已付款
5,10091,运动跑步鞋男款,运动鞋,1,199.0,199.0,2026-07-23 11:48:23,四川,成都,已完成
6,10092,维C咀嚼片100片,保健品,2,39.9,79.8,2026-07-23 12:20:14,湖北,武汉,已取消
7,10093,USB-C数据线2米,数码配件,3,15.0,45.0,2026-07-23 13:05:49,福建,厦门,已发货
8,10094,全麦面包1kg装,食品零食,1,22.5,22.5,2026-07-23 14:18:36,山东,青岛,已完成
9,10095,便携式榨汁机,小家电,1,129.0,129.0,2026-07-23 15:42:11,河南,郑州,已付款
10,10096,防晒喷雾SPF50+,美妆护肤,2,49.9,99.8,2026-07-23 16:30:28,湖南,长沙,已发货
11,10097,瑜伽垫加厚防滑,运动户外,1,69.0,69.0,2026-07-23 17:15:03,陕西,西安,已完成
12,10098,儿童绘本套装10册,图书音像,1,88.0,88.0,2026-07-23 18:08:45,甘肃,平凉,已付款
13,10099,车载手机支架,汽车配件,1,25.0,25.0,2026-07-23 19:22:17,辽宁,沈阳,已发货
14,10100,电动牙刷套装,个护健康,1,159.0,159.0,2026-07-23 20:55:39,安徽,NaN,已完成
15,10100,电动牙刷套装,个护健康,1,159.0,159.0,2026-07-23 20:55:39,安徽,合肥,已完成